#ifndef _ZONES_H
#define _ZONES_H

#include "types.h"

extern const utz_rule_packed_t utz_zone_rules[39];
extern const char utz_zone_abrevs[209];

#define MAX_ABREV_FORMATTER_LEN 5

extern const uzone_packed_t utz_zone_defns[47];
#define UTZ_ADELAIDE            &utz_zone_defns[ 31]
#define UTZ_AHMEDABAD           &utz_zone_defns[ 24]
#define UTZ_ANCHORAGE           &utz_zone_defns[  4]
#define UTZ_ANKARA              &utz_zone_defns[ 40]
#define UTZ_ATLANTA             &utz_zone_defns[ 12]
#define UTZ_AUCKLAND            &utz_zone_defns[ 43]
#define UTZ_BANGALORE           &utz_zone_defns[ 24]
#define UTZ_BANGKOK             &utz_zone_defns[ 18]
#define UTZ_BARCELONA           &utz_zone_defns[ 38]
#define UTZ_BEIJING             &utz_zone_defns[ 27]
#define UTZ_BELGRADE            &utz_zone_defns[ 38]
#define UTZ_BELO_HORIZONTE      &utz_zone_defns[ 16]
#define UTZ_BERLIN              &utz_zone_defns[ 38]
#define UTZ_BOSTON              &utz_zone_defns[ 12]
#define UTZ_BRAZZAVILLE         &utz_zone_defns[  1]
#define UTZ_BRISBANE            &utz_zone_defns[ 32]
#define UTZ_BUENOS_AIRES        &utz_zone_defns[  5]
#define UTZ_CAIRO               &utz_zone_defns[  0]
#define UTZ_CALCUTTA            &utz_zone_defns[ 24]
#define UTZ_CHANGZHOU           &utz_zone_defns[ 27]
#define UTZ_CHENGDU             &utz_zone_defns[ 27]
#define UTZ_CHENNAI             &utz_zone_defns[ 24]
#define UTZ_CHICAGO             &utz_zone_defns[  6]
#define UTZ_CHONGQING           &utz_zone_defns[ 27]
#define UTZ_DARWIN              &utz_zone_defns[ 33]
#define UTZ_DELHI               &utz_zone_defns[ 24]
#define UTZ_DENVER              &utz_zone_defns[  7]
#define UTZ_DUBAI               &utz_zone_defns[ 19]
#define UTZ_GUADALAJARA         &utz_zone_defns[ 11]
#define UTZ_GUAM                &utz_zone_defns[ 44]
#define UTZ_GUANGZHOU           &utz_zone_defns[ 27]
#define UTZ_HALIFAX             &utz_zone_defns[  8]
#define UTZ_HAMBURG             &utz_zone_defns[ 38]
#define UTZ_HANGZHOU            &utz_zone_defns[ 27]
#define UTZ_HARARE              &utz_zone_defns[  2]
#define UTZ_HARBIN              &utz_zone_defns[ 27]
#define UTZ_HELSINKI            &utz_zone_defns[ 39]
#define UTZ_HOBART              &utz_zone_defns[ 34]
#define UTZ_HONG_KONG           &utz_zone_defns[ 20]
#define UTZ_HONOLULU            &utz_zone_defns[ 45]
#define UTZ_HOUSTON             &utz_zone_defns[  6]
#define UTZ_HYDERABAD           &utz_zone_defns[ 24]
#define UTZ_INLAND_EMPIRE       &utz_zone_defns[  9]
#define UTZ_ISTANBUL            &utz_zone_defns[ 40]
#define UTZ_JERUSALEM           &utz_zone_defns[ 21]
#define UTZ_JINAN               &utz_zone_defns[ 27]
#define UTZ_KARACHI             &utz_zone_defns[ 22]
#define UTZ_KATMANDU            &utz_zone_defns[ 23]
#define UTZ_KOLKATA             &utz_zone_defns[ 24]
#define UTZ_KUWAIT              &utz_zone_defns[ 25]
#define UTZ_LAHORE              &utz_zone_defns[ 22]
#define UTZ_LONDON              &utz_zone_defns[ 41]
#define UTZ_LOS_ANGELES         &utz_zone_defns[  9]
#define UTZ_MADRID              &utz_zone_defns[ 38]
#define UTZ_MANAUS              &utz_zone_defns[ 10]
#define UTZ_MEXICO_CITY         &utz_zone_defns[ 11]
#define UTZ_MIAMI               &utz_zone_defns[ 12]
#define UTZ_MIDWAY              &utz_zone_defns[ 46]
#define UTZ_MILAN               &utz_zone_defns[ 38]
#define UTZ_MOSCOW              &utz_zone_defns[ 42]
#define UTZ_MUMBAI              &utz_zone_defns[ 24]
#define UTZ_MUNICH              &utz_zone_defns[ 38]
#define UTZ_NAGOYA              &utz_zone_defns[ 29]
#define UTZ_NAIROBI             &utz_zone_defns[  3]
#define UTZ_NANCHANG            &utz_zone_defns[ 27]
#define UTZ_NANJING             &utz_zone_defns[ 27]
#define UTZ_NEW_YORK            &utz_zone_defns[ 12]
#define UTZ_OSAKA               &utz_zone_defns[ 29]
#define UTZ_PERTH               &utz_zone_defns[ 35]
#define UTZ_PHILADELPHIA        &utz_zone_defns[ 12]
#define UTZ_PHOENIX             &utz_zone_defns[ 13]
#define UTZ_PUNE                &utz_zone_defns[ 24]
#define UTZ_QINGDAO             &utz_zone_defns[ 27]
#define UTZ_RANGOON             &utz_zone_defns[ 30]
#define UTZ_REGINA              &utz_zone_defns[ 14]
#define UTZ_RHINERUHR           &utz_zone_defns[ 38]
#define UTZ_RIO_DE_JANEIRO      &utz_zone_defns[ 16]
#define UTZ_ROME                &utz_zone_defns[ 38]
#define UTZ_SAN_FRANCISCO       &utz_zone_defns[  9]
#define UTZ_SANTIAGO            &utz_zone_defns[ 15]
#define UTZ_SAO_PAULO           &utz_zone_defns[ 16]
#define UTZ_SARAJEVO            &utz_zone_defns[ 38]
#define UTZ_SEOUL               &utz_zone_defns[ 26]
#define UTZ_SHANGHAI            &utz_zone_defns[ 27]
#define UTZ_SHANTOU             &utz_zone_defns[ 27]
#define UTZ_SHENYANG            &utz_zone_defns[ 27]
#define UTZ_SHENZHEN            &utz_zone_defns[ 27]
#define UTZ_ST_JOHNS            &utz_zone_defns[ 17]
#define UTZ_STUTTGART           &utz_zone_defns[ 38]
#define UTZ_SURAT               &utz_zone_defns[ 24]
#define UTZ_SYDNEY              &utz_zone_defns[ 36]
#define UTZ_TAIPEI              &utz_zone_defns[ 27]
#define UTZ_TEHRAN              &utz_zone_defns[ 28]
#define UTZ_TIANJIN             &utz_zone_defns[ 27]
#define UTZ_TIJUANA             &utz_zone_defns[  9]
#define UTZ_TOKYO               &utz_zone_defns[ 29]
#define UTZ_UNIVERSAL           &utz_zone_defns[ 37]
#define UTZ_WASHINGTON_DC       &utz_zone_defns[ 12]
#define UTZ_WENZHOU             &utz_zone_defns[ 27]
#define UTZ_WUHAN               &utz_zone_defns[ 27]
#define UTZ_XIAN                &utz_zone_defns[ 27]
#define UTZ_ZHENGZHOU           &utz_zone_defns[ 27]

#define UTZ_NUM_ZONE_NAMES 102
#define UTZ_MAX_ZONE_NAME_LEN 17

extern const char utz_zone_names[972];
#endif /* _ZONES_H */